=== codecurve/fieldml.api/Fieldml_0.3.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="fieldml"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:fmlmeta="http://www.fieldml.org/metadata/0.3#"
    >
    
    <xs:import schemaLocation="Fieldml_0.3_meta.xsd" namespace="http://www.fieldml.org/metadata/0.3#"/>

    <xs:complexType name="FieldmlObject_Type">
        <xs:complexContent >
            <xs:extension base="fmlmeta:FieldmlRdfTargetType">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="BindMapEntry_Type">
        <xs:attribute name="variable" type="xs:string" />
        <xs:attribute name="source" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="BindMapIndexEntry_Type">
        <xs:attribute name="variable" type="xs:string" />
        <xs:attribute name="indexNumber" type="xs:positiveInteger" />
    </xs:complexType>

    <xs:complexType name="BindMap_Type">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Bind" type="BindMapEntry_Type" />
            <xs:element name="BindIndex" type="BindMapIndexEntry_Type" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ComponentEvaluatorsEntry_Type">
        <xs:attribute name="number" type="xs:positiveInteger" />
        <xs:attribute name="evaluator" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="ComponentEvaluators_Type">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ComponentEvaluator" type="ComponentEvaluatorsEntry_Type" />
        </xs:choice>
        <xs:attribute name="default" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="SimpleMapEntry_Type">
        <xs:attribute name="key" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="SimpleMap_Type">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="SimpleMapEntry" type="SimpleMapEntry_Type" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ElementMapEntry_Type">
        <xs:attribute name="number" type="xs:string" />
        <xs:attribute name="evaluator" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="ElementMap_Type">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ElementEvaluator" type="ElementMapEntry_Type" />
        </xs:choice>
        <xs:attribute name="default" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="DefaultSimpleMap_Type">
        <xs:complexContent>
            <xs:extension base="SimpleMap_Type">
                <xs:attribute name="default" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="VariableListEntry_Type">
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="VariableList_Type">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Variable" type="VariableListEntry_Type" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="EvaluatorListEntry_Type">
        <xs:attribute name="evaluator" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="IndexEvaluatorList_Type">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="IndexEvaluator" type="EvaluatorListEntry_Type" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="MemberRange_Type">
        <xs:attribute name="min" type="xs:nonNegativeInteger" />
        <xs:attribute name="max" type="xs:nonNegativeInteger" />
        <xs:attribute name="stride" type="xs:positiveInteger" use="optional"/>
    </xs:complexType>

    <xs:complexType name="MemberList_Type">
      <xs:simpleContent>
        <xs:extension base="xs:string">
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="EnsembleMembers_Type">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="MemberList" type="MemberList_Type" />
            <xs:element name="MemberRange" type="MemberRange_Type" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="EnsembleType_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlObject_Type">
                <xs:sequence>
                    <xs:element name="Members" type="EnsembleMembers_Type" minOccurs="1" maxOccurs="1" />
                </xs:sequence>
                <xs:attribute name="isComponentEnsemble" type="xs:boolean" use="optional" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ContinuousType_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlObject_Type">
                <xs:attribute name="componentEnsemble" type="xs:string" use="optional" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="MeshType_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlObject_Type">
                <xs:sequence>
                    <xs:element name="Elements" type="EnsembleMembers_Type" minOccurs="1" maxOccurs="1" />
                    <xs:element name="Shapes" type="DefaultSimpleMap_Type" minOccurs="1" maxOccurs="1" />
                </xs:sequence>
                <xs:attribute name="xiComponent" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="FieldmlEvaluator_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlObject_Type">
                <xs:sequence>
                    <xs:element name="Variables" type="VariableList_Type" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
                <xs:attribute name="valueType" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AbstractEvaluator_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlEvaluator_Type" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ExternalEvaluator_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlEvaluator_Type" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ReferenceEvaluator_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlEvaluator_Type">
                <xs:sequence>
                    <xs:element name="Bindings" type="BindMap_Type" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
                <xs:attribute name="evaluator" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="PiecewiseEvaluator_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlEvaluator_Type">
                <xs:sequence>
                    <xs:element name="Bindings" type="BindMap_Type" minOccurs="0" maxOccurs="1" />
                    <xs:element name="ElementEvaluators" type="ElementMap_Type" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="FileData_Type">
        <xs:attribute name="file" type="xs:string" />
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute name="offset" type="xs:nonNegativeInteger" />
    </xs:complexType>

    <xs:complexType name="InlineData_Type">
      <xs:simpleContent>
        <xs:extension base="xs:string">
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="Swizzle_Type">
      <xs:simpleContent>
        <xs:extension base="xs:string">
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="DataLocation_Type">
        <xs:choice>
            <xs:element name="FileData" type="FileData_Type" />
            <xs:element name="InlineData" type="InlineData_Type" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="SemidenseData_Type">
        <xs:sequence>
            <xs:element name="DenseIndexes" type="IndexEvaluatorList_Type" minOccurs="0" maxOccurs="1" />
            <xs:element name="SparseIndexes" type="IndexEvaluatorList_Type" minOccurs="0" maxOccurs="1" />
            <xs:element name="DataLocation" type="DataLocation_Type" minOccurs="1" maxOccurs="1" />
            <xs:element name="Swizzle" type="Swizzle_Type" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ParameterEvaluator_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlEvaluator_Type">
                <xs:choice>
                    <xs:element name="SemidenseData" type="SemidenseData_Type" minOccurs="1" maxOccurs="1" />
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AggregateEvaluator_Type">
        <xs:complexContent>
            <xs:extension base="FieldmlEvaluator_Type">
                <xs:sequence>
                    <xs:element name="Bindings" type="BindMap_Type" minOccurs="0" maxOccurs="1" />
                    <xs:element name="ComponentEvaluators" type="ComponentEvaluators_Type" minOccurs="1" maxOccurs="1" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Region_Type">
        <xs:complexContent >
            <xs:extension base="fmlmeta:FieldmlRdfTargetType">
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="EnsembleType" type="EnsembleType_Type" />
                    <xs:element name="ContinuousType" type="ContinuousType_Type" />
                    <xs:element name="MeshType" type="MeshType_Type" />
                    <xs:element name="AbstractEvaluator" type="AbstractEvaluator_Type" />
                    <xs:element name="ExternalEvaluator" type="ExternalEvaluator_Type" />
                    <xs:element name="ReferenceEvaluator" type="ReferenceEvaluator_Type" />
                    <xs:element name="PiecewiseEvaluator" type="PiecewiseEvaluator_Type" />
                    <xs:element name="ParametersEvaluator" type="ParameterEvaluator_Type" />
                    <xs:element name="AggregateEvaluator" type="AggregateEvaluator_Type" />
                </xs:choice>
                <xs:attribute name="name" type="xs:string" />
                <xs:attribute name="library" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Fieldml_Type">
        <xs:complexContent >
            <xs:extension base="fmlmeta:FieldmlRdfTargetType">
                <xs:choice minOccurs="1" maxOccurs="1">
                    <xs:element name="Region" type="Region_Type" />
                </xs:choice>
                <xs:attribute name="version" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:element name="Fieldml" type="Fieldml_Type"/>
    
</xs:schema>

=== codecurve/fieldml.api/FieldML_Library.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Fieldml version="0.3_alpha" xsi:noNamespaceSchemaLocation="Fieldml_0.3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <Region name="library">
  <ContinuousType name="real.1d"/>
  <AbstractEvaluator name="real.1d.variable" valueType="real.1d"/>
  
  <ContinuousType name="real.2d">
    <Components name="real.2d.component" count="2"/>
  </ContinuousType>
  <AbstractEvaluator name="real.2d.component.variable" valueType="real.2d.component"/>
  <AbstractEvaluator name="real.2d.variable" valueType="real.2d"/>

  <ContinuousType name="real.3d">
    <Components name="real.3d.component" count="3"/>
  </ContinuousType>
  <AbstractEvaluator name="real.3d.component.variable" valueType="real.3d.component"/>
  <AbstractEvaluator name="real.3d.variable" valueType="real.3d"/>

  <ContinuousType name="chart.1d">
    <Components name="chart.1d.component" count="1"/>
  </ContinuousType>
  <AbstractEvaluator name="chart.1d.component.variable" valueType="chart.1d.component"/>
  <AbstractEvaluator name="chart.1d.variable" valueType="chart.1d"/>

  <ContinuousType name="chart.2d">
    <Components name="chart.2d.component" count="2"/>
  </ContinuousType>
  <AbstractEvaluator name="chart.2d.component.variable" valueType="chart.2d.component"/>
  <AbstractEvaluator name="chart.2d.variable" valueType="chart.2d"/>

  <ContinuousType name="chart.3d">
    <Components name="chart.3d.component" count="3"/>
  </ContinuousType>
  <AbstractEvaluator name="chart.3d.component.variable" valueType="chart.3d.component"/>
  <AbstractEvaluator name="chart.3d.variable" valueType="chart.3d"/>

  <EnsembleType name="localNodes.1d.line2">
   <Members>
    <MemberRange min="1" max="2"/>
   </Members>
  </EnsembleType>
  <AbstractEvaluator name="localNodes.1d.line2.variable" valueType="localNodes.1d.line2"/>

  <ContinuousType name="parameters.1d.linearLagrange">
    <Components name="parameters.1d.linearLagrange.component" count="2"/>
  </ContinuousType>
  <AbstractEvaluator name="parameters.1d.linearLagrange.component.variable" valueType="parameters.1d.linearLagrange.component"/>
  <AbstractEvaluator name="parameters.1d.linearLagrange.variable" valueType="parameters.1d.linearLagrange"/>

  <ExternalEvaluator name="interpolator.1d.unit.linearLagrange" valueType="real.1d">
    <Variables>
      <Variable name="chart.1d.variable"/>
      <Variable name="parameters.1d.linearLagrange.variable"/>
    </Variables>
  </ExternalEvaluator>

  <EnsembleType name="localNodes.1d.line3">
   <Members>
    <MemberRange min="1" max="3"/>
   </Members>
  </EnsembleType>
  <AbstractEvaluator name="localNodes.1d.line3.variable" valueType="localNodes.1d.line3"/>
  
  <ContinuousType name="parameters.1d.quadraticLagrange">
    <Components name="parameters.1d.quadraticLagrange.component" count="3"/>
  </ContinuousType>
  <AbstractEvaluator name="parameters.1d.quadraticLagrange.component.variable" valueType="parameters.1d.quadraticLagrange.component"/>
  <AbstractEvaluator name="parameters.1d.quadraticLagrange.variable" valueType="parameters.1d.quadraticLagrange"/>

  <ExternalEvaluator name="interpolator.1d.unit.quadraticLagrange" valueType="real.1d">
    <Variables>
      <Variable name="chart.1d.variable"/>
      <Variable name="parameters.1d.quadraticLagrange.variable"/>
    </Variables>
  </ExternalEvaluator>

  <EnsembleType name="localNodes.2d.square2x2">
   <Members>
    <MemberRange min="1" max="4"/>
   </Members>
  </EnsembleType>
  <AbstractEvaluator name="localNodes.2d.square2x2.variable" valueType="localNodes.2d.square2x2"/>

  <ContinuousType name="parameters.2d.bilinearLagrange">
    <Components name="parameters.2d.bilinearLagrange.component" count="4"/>
  </ContinuousType>
  <AbstractEvaluator name="parameters.2d.bilinearLagrange.variable" valueType="parameters.2d.bilinearLagrange"/>
  <AbstractEvaluator name="parameters.2d.bilinearLagrange.component.variable" valueType="parameters.2d.bilinearLagrange.component"/>

  <ExternalEvaluator name="interpolator.2d.unit.bilinearLagrange" valueType="real.1d">
    <Variables>
      <Variable name="chart.2d.variable"/>
      <Variable name="parameters.2d.bilinearLagrange.variable"/>
    </Variables>
  </ExternalEvaluator>

  <EnsembleType name="localNodes.2d.square3x3">
   <Members>
    <MemberRange min="1" max="9"/>
   </Members>
  </EnsembleType>
  <AbstractEvaluator name="localNodes.2d.square3x3.variable" valueType="localNodes.2d.square3x3"/>
  
  <ContinuousType name="parameters.2d.biquadraticLagrange">
    <Components name="parameters.2d.biquadraticLagrange.component" count="9"/>
  </ContinuousType>
  <AbstractEvaluator name="parameters.2d.biquadraticLagrange.variable" valueType="parameters.2d.biquadraticLagrange"/>
  <AbstractEvaluator name="parameters.2d.biquadraticLagrange.component.variable" valueType="parameters.2d.biquadraticLagrange.component"/>

  <ExternalEvaluator name="interpolator.2d.unit.biquadraticLagrange" valueType="real.1d">
    <Variables>
      <Variable name="chart.2d.variable"/>
      <Variable name="parameters.2d.biquadraticLagrange.variable"/>
    </Variables>
  </ExternalEvaluator>

  <EnsembleType name="localNodes.3d.cube2x2x2">
   <Members>
    <MemberRange min="1" max="8"/>
   </Members>
  </EnsembleType>
  <AbstractEvaluator name="localNodes.3d.cube2x2x2.variable" valueType="localNodes.3d.cube2x2x2"/>

  <ContinuousType name="parameters.3d.trilinearLagrange">
    <Components name="parameters.3d.trilinearLagrange.component" count="8"/>
  </ContinuousType>
  <AbstractEvaluator name="parameters.3d.trilinearLagrange.variable" valueType="parameters.3d.trilinearLagrange"/>

  <ExternalEvaluator name="interpolator.3d.unit.trilinearLagrange" valueType="real.1d">
    <Variables>
      <Variable name="chart.3d.variable"/>
      <Variable name="parameters.3d.trilinearLagrange.variable"/>
    </Variables>
  </ExternalEvaluator>

  <EnsembleType name="localNodes.3d.cube3x3x3">
   <Members>
    <MemberRange min="1" max="27"/>
   </Members>
  </EnsembleType>
  <AbstractEvaluator name="localNodes.3d.cube3x3x3.variable" valueType="localNodes.3d.cube3x3x3"/>
  
  <ContinuousType name="parameters.3d.triquadraticLagrange">
    <Components name="parameters.3d.triquadraticLagrange.component" count="27"/>
  </ContinuousType>
  <AbstractEvaluator name="parameters.3d.triquadraticLagrange.variable" valueType="parameters.3d.triquadraticLagrange"/>
  <AbstractEvaluator name="parameters.3d.triquadraticLagrange.component.variable" valueType="parameters.3d.triquadraticLagrange.component"/>

  <ExternalEvaluator name="interpolator.3d.unit.triquadraticLagrange" valueType="real.1d">
    <Variables>
      <Variable name="chart.3d.variable"/>
      <Variable name="parameters.3d.triquadraticLagrange.variable"/>
    </Variables>
  </ExternalEvaluator>

  <ContinuousType name="coordinates.rc.1d"/>
  <AbstractEvaluator name="coordinates.rc.1d.variable" valueType="coordinates.rc.1d"/>

  <ContinuousType name="coordinates.rc.2d">
    <Components name="coordinates.rc.2d.component" count="2"/>
  </ContinuousType>
  <AbstractEvaluator name="coordinates.rc.2d.variable" valueType="coordinates.rc.2d"/>
  <AbstractEvaluator name="coordinates.rc.2d.component.variable" valueType="coordinates.rc.2d.component"/>

  <ContinuousType name="coordinates.rc.3d">
    <Components name="coordinates.rc.3d.component" count="3"/>
  </ContinuousType>
  <AbstractEvaluator name="coordinates.rc.3d.variable" valueType="coordinates.rc.3d"/>
  <AbstractEvaluator name="coordinates.rc.3d.component.variable" valueType="coordinates.rc.3d.component"/>

  <ContinuousType name="parameters.1d.cubicHermite">
    <Components name="parameters.1d.cubicHermite.component" count="4"/>
  </ContinuousType>
  <AbstractEvaluator name="parameters.1d.cubicHermite.variable" valueType="parameters.1d.cubicHermite"/>
  <AbstractEvaluator name="parameters.1d.cubicHermite.component.variable" valueType="parameters.1d.cubicHermite.component"/>
  <AbstractEvaluator name="parameters.1d.cubicHermiteScaling.variable" valueType="parameters.1d.cubicHermite"/>

  <ExternalEvaluator name="interpolator.1d.unit.cubicHermite" valueType="real.1d">
    <Variables>
      <Variable name="chart.1d.variable"/>
      <Variable name="parameters.1d.cubicHermite.variable"/>
    </Variables>
  </ExternalEvaluator>

  <ExternalEvaluator name="interpolator.1d.unit.cubicHermiteScaled" valueType="real.1d">
    <Variables>
      <Variable name="chart.1d.variable"/>
      <Variable name="parameters.1d.cubicHermite.variable"/>
      <Variable name="parameters.1d.cubicHermiteScaling.variable"/>
    </Variables>
  </ExternalEvaluator>

  <ContinuousType name="parameters.2d.bicubicHermite">
    <Components name="parameters.2d.bicubicHermite.component" count="16"/>
  </ContinuousType>
  <AbstractEvaluator name="parameters.2d.bicubicHermite.variable" valueType="parameters.2d.bicubicHermite"/>
  <AbstractEvaluator name="parameters.2d.bicubicHermite.component.variable" valueType="parameters.2d.bicubicHermite.component"/>
  <AbstractEvaluator name="parameters.2d.bicubicHermiteScaling.variable" valueType="parameters.2d.bicubicHermite"/>

  <ExternalEvaluator name="interpolator.2d.unit.bicubicHermite" valueType="real.1d">
    <Variables>
      <Variable name="chart.2d.variable"/>
      <Variable name="parameters.2d.bicubicHermite.variable"/>
    </Variables>
  </ExternalEvaluator>

  <ExternalEvaluator name="interpolator.2d.unit.bicubicHermiteScaled" valueType="real.1d">
    <Variables>
      <Variable name="chart.2d.variable"/>
      <Variable name="parameters.2d.bicubicHermite.variable"/>
      <Variable name="parameters.2d.bicubicHermiteScaling.variable"/>
    </Variables>
  </ExternalEvaluator>

  <ContinuousType name="parameters.3d.tricubicHermite">
